# Generated by Django 4.2.2 on 2023-06-27 15:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category_name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('service_description', models.TextField(max_length=2000)),
                ('service_location', models.TextField(max_length=400)),
                ('service_images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='media/service_images'), blank=True, size=None)),
                ('service_service_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.servicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ReservedDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reserved', models.DateField(max_length=20)),
                ('slot_reserved', models.IntegerField()),
                ('service_reserved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='service.service')),
            ],
            options={
                'verbose_name_plural': 'ReservedDates',
            },
        ),
    ]
