# Generated by Django 4.2.2 on 2023-06-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserveddates',
            options={},
        ),
    ]
