# Generated by Django 4.2.2 on 2023-06-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserveddates',
            options={},
        ),
    ]
