# Generated by Django 4.2.2 on 2023-06-30 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_reserveddates_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicecategory'),
        ),
    ]
