# Generated by Django 4.2.2 on 2023-06-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_service_service_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='service_category_name',
            field=models.CharField(max_length=50),
        ),
    ]
