# Generated by Django 4.2.2 on 2023-06-27 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_servicecategory_service_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveddates',
            name='service_reserved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
    ]
