# Generated by Django 4.2.2 on 2023-06-27 21:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_reserveddates_service_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='media/service_images'), blank=True, size=None),
        ),
    ]
