# Generated by Django 4.2.2 on 2023-06-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_service_service_provider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
