# Generated by Django 4.2.2 on 2023-07-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_alter_service_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
