# Generated by Django 4.2.2 on 2023-07-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_service_service_rate_servicerate'),
        ('service', '0015_alter_service_service_provider'),
    ]

    operations = [
    ]
