# Generated by Django 4.2.2 on 2023-07-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_alter_service_service_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_service_category',
            field=models.CharField(choices=[('Hall-Reservation', 'Hall-Reservation'), ('Car-Rental', 'Car-Rental'), ('Photo-Session', 'Photo-Session'), ('MakeUp-Artist', 'MakeUp-Artist')], max_length=20),
        ),
    ]
