# Generated by Django 4.2.2 on 2023-07-05 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_merge_20230703_1518'),
        ('service', '0017_alter_service_service_service_category'),
    ]

    operations = [
    ]
