# Generated by Django 4.2.2 on 2023-06-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, unique=True)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='media/users_images')),
            ],
        ),
    ]
