# Generated by Django 4.2.2 on 2023-06-27 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Please enter a valid Egyptian phone number', regex='^01[0-2]{1}[0-9]{8}$')]),
        ),
    ]
