# Generated by Django 4.2.2 on 2023-06-30 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_customer_image'),
        ('customer', '0005_customer_created_at'),
    ]

    operations = [
    ]
