# Generated by Django 4.2.2 on 2023-06-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_merge_20230701_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/users_images'),
        ),
    ]
