# Generated by Django 4.2.2 on 2023-06-28 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_is_provider_alter_customer_customer_phone'),
        ('service', '0008_service_service_provider_and_more'),
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='customer_user',
        ),
        migrations.RemoveField(
            model_name='package',
            name='services',
        ),
        migrations.AddField(
            model_name='package',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='package',
            name='service_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service.service'),
        ),
    ]
