# Generated by Django 4.2.2 on 2023-06-28 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_created_at'),
        ('service', '0011_delete_servicecategory'),
        ('package', '0003_package_created_at_alter_package_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='package',
            name='service_id',
        ),
        migrations.AddField(
            model_name='package',
            name='customer_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='package',
            name='services',
            field=models.ManyToManyField(related_name='services', to='service.service'),
        ),
    ]
