# Generated by Django 4.2.2 on 2023-06-28 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_created_at'),
        ('package', '0004_remove_package_customer_id_remove_package_service_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='customer_user',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
            preserve_default=False,
        ),
    ]
