# Generated by Django 4.2.2 on 2023-06-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0002_alter_serviceprovider_provider_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='provider_service_category',
        ),
    ]
