# Generated by Django 4.2.2 on 2023-06-28 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0003_remove_serviceprovider_provider_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
